apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
  labels:
    app: postgres-database
spec:
  ports:
    - port: 5431
      targetPort: 5431
  selector:
    app: postgres-database
  clusterIP: None 