apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - env:
        - name: DB_ADDR
          value: postgres-keycloak
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-database
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-username
        - name: DB_VENDOR
          value: POSTGRES
        - name: KEYCLOAK_PASSWORD
          value: "123456789"
          # valueFrom:
          #   secretKeyRef:
          #     name: keycloak-secret
          #     key: keycloak-password
        - name: KEYCLOAK_USER
          value: "hieudx1"
          # valueFrom:
          #   secretKeyRef:
          #     name: keycloak-secret
          #     key: keycloak-username
        - name: KC_USER
          value: "hieudx1"
          # valueFrom:
          #   secretKeyRef:
          #     name: keycloak-secret
          #     key: keycloak-password
        - name: KC_PASSWORD
          value: "123456789"
          # valueFrom:
          #   secretKeyRef:
          #     name: keycloak-secret
          #     key: keycloak-username
        - name: KC_HTTP_PORT
          value: "8080"
        image: quay.io/keycloak/keycloak:10.0.1
        imagePullPolicy: "Always"
        name: keycloak
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        resources: 
          requests:
              memory: "64Mi"
              cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "600m"
      restartPolicy: Always
      serviceAccountName: ""
