apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-bank
spec:
  selector:
    matchLabels:
      app: core-bank
  replicas: 1
  template:
    metadata:
      labels:
        app: core-bank
    spec:
      containers:
        - name: core-bank
          image: docker.io/0967840437/core-bank:3
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

            - name: REGISTRY_HOST 
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  registry-host

