apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image:  bitnami/mysql
          name: mysql
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456789"
            - name: MYSQL_USER
              value: "hieudx1"
            - name: MYSQL_PASSWORD
              value: "123456789"
            - name: MYSQL_DATABASE
              value: "core_bank"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
